In [4]:
import pandas as pd

In [6]:
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")
aisles = pd.read_csv("aisles.csv")
departments = pd.read_csv("departments.csv")
order_products__prior = pd.read_csv("order_products__prior.csv")
order_products__train = pd.read_csv("order_products__train.csv")

print("Datasets Loaded")

Datasets Loaded

In [7]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [8]:
products_full = products.merge(aisles, on="aisle_id")
products_full = products_full.merge(departments, on="department_id")

products_full.head()

,product_id,product_name,aisle_id,department_id,aisle,department
0,1,Chocolate Sandwich Cookies,61,19,cookies cakes,snacks
1,2,All-Seasons Salt,104,13,spices seasonings,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,tea,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,frozen meals,frozen
4,5,Green Chile Anytime Sauce,5,13,marinades meat preparation,pantry

In [10]:
order_products = pd.concat([order_products__prior, order_products__train])

order_products.shape

(33819106, 4)

In [11]:
order_details = order_products.merge(products_full, on="product_id")

final_data = order_details.merge(orders, on="order_id")

final_data.head()

MemoryError: cannot allocate memory for array

In [ ]:
final_data["product_name"].value_counts().head(10)

final_data.groupby("department")["order_id"].count()

final_data["user_id"].value_counts().head(10)

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
"postgresql://postgres:password@localhost:5432/etl_project"
)

final_data.to_sql(
"instacart_orders",
engine,
if_exists="replace",
index=False
)

print("Data Loaded into PostgreSQL")